---
title: "St Peters predictors"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    self_contained: true
---


Donor pool equal to St Peters with respect to:  

- Phase of education  
- Region  
- Level of urbanicity  
- Denomination  
- Completeness of observations on the outcome measure  
- Note: Boarding schools are excluded from donor pool

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)
# empty work space
rm(list = ls())
gc()

# load libraries
library(kableExtra)
library(dplyr)
library(data.table)
library(ggplot2)

devtools::source_url("https://github.com/stefaniemeliss/scm_feasibility/blob/main/functions.R?raw=TRUE")

# define directories
dir <- getwd()
dir <- gsub("/02_scm/filtering_v1", "", dir)
dir_data <- file.path(dir, "data")
dir_misc <- file.path(dir, "misc")

# copy data #
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_swf.csv"), dir_data, overwrite = T)
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_pupils.csv"), dir_data, overwrite = T)
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_establishments_search.csv"), dir_data, overwrite = T)

# load data #

swf <- fread(file.path(dir_data, "data_swf.csv"))
pup <- fread(file.path(dir_data, "data_pupils.csv"))
est <- fread(file.path(dir_data, "data_establishments_search.csv"), na.strings = "")

# process data establishments #

# get spc data from treated school
id_treated <- 3344650

est_treated <- est %>% 
  filter(laestab == id_treated) %>%
  mutate(status = "treated") %>% 
  as.data.frame()

# get donor pool data
est_cont <- est %>%
  filter(laestab != id_treated,
         ! grepl("Boarding school", boarders_name),
         phaseofeducation_name %in% unique(c(est_treated$phaseofeducation_name)),
         gor_name %in% unique(c(est_treated$gor_name)),
         urbanicity %in% c(unique(est_treated$urbanicity)), # coded as urban vs rural
         #idaci_decile %in% unique(c(est_treated$idaci_decile)), 
         religiouscharacter_christian %in% unique(c(est_treated$religiouscharacter_christian))) %>%
  mutate(status = "untreated") %>% 
  as.data.frame()

# save urn and laebstab
list_laestab <- c(unique(est_cont[, "laestab"]), unique(est_treated[, "laestab"]))
list_urn <- c(unique(est_cont[, "urn"]), unique(est_treated[, "urn"]))

```

```{r working_chunk, echo=FALSE, eval=F}
# Remove rows with NA for dependent variable and add obs_count
df_plt <- x %>%
  filter(!is.na(get(var))) %>%
  group_by(laestab) %>%
  mutate(
    obs_count = sum(!is.na(get(var)))) %>%
  ungroup() %>%
  select(-one_of(c("region_code", "new_la_code", "old_la_code")))

# Filter for rows where obs_count matches the treated id
df_plt <- df_plt %>%
  filter(obs_count == unique(df_plt$obs_count[df_plt$laestab == id_treated]))

dep_var = var

# look at histogram by year
plt <- ggplot(data = df_plt, aes(x = get(dep_var))) + 
  geom_histogram(bins = 25) + 
  facet_wrap(~get(group_var)) + 
  ambition_theme + 
  ylab("Count") +
  xlab(paste(y_lab, "-", trans)) + theme(axis.text.x = element_blank())
print(plt)

# compute descriptives per year
out <- rbind(
  do.call("rbind",psych::describeBy(df_plt[, dep_var], group = df_plt[, group_var]))
)
# edit output
out$vars <- NULL
out <- round(out, 3)
# print output
kbl(out, caption = paste("Descriptives of variable", var, trans)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T) %>%
  print()

# augmented Dickey-Fuller test
tseries::adf.test(na.omit(out$mean), k = 0) %>%
  print()


# plot overall time series
n_donors = length(unique(df_plt$laestab[df_plt$idx_donor]))
plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab)) +
  geom_line(data = df_plt[df_plt$idx_donor,], aes(col = paste("Donor schools"))) + 
  geom_line(data = df_plt[df_plt$idx_treat,], aes(col = "St Peters"), linewidth =.8) +
  ambition_theme + 
  theme(legend.title = element_blank(), 
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab(paste(y_lab, "-", trans)) + xlab(x_lab) +
  labs(caption = paste0("Note. N = ", n_donors, " donor schools.")) +
  scale_color_manual(
    breaks=c("St Peters", "Donor schools"),
    values=c("Donor schools" = navy40, "St Peters" = coral))
print(plt)


# Trellis plot
plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab, col = status, fill = status)) +
  geom_point() + 
  geom_line() +
  geom_area(alpha=0.6) +
  facet_wrap("laestab") +
  scale_color_manual(values = c(dominant_col, navy40)) + scale_fill_manual(values = c(dominant_col, navy40)) +
  ambition_theme + theme(legend.position = "none",  
                         axis.text.x = element_blank()
  ) +
  ylab(paste(y_lab, "-", trans)) +
  xlab(x_lab) #+ labs(caption = paste0("The treated school is ", id_treated, "."))
print(plt)

# plot yearly average
out[, group_var] <- row.names(out)
plt <- ggplot(data = out, aes(x = time_period, y = mean)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean-1.96*se, ymax = mean+1.96*se), width=.2,
                position=position_dodge(.9)) +
  geom_line(group = 1) + 
  ambition_theme + theme(legend.position = "none",  
                         axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab(paste(y_lab, "-", trans)) +
  xlab(x_lab)
print(plt)

# within school stats
tmp <- df_plt %>% group_by(laestab) %>%
  summarise(#obs_per_school = sum(!is.na(get(dep_var))),
    vars = paste(var, "-" ,trans),
    within_school_mean = mean(get(dep_var), na.rm = T),
    within_school_sd = sd(get(dep_var), na.rm = T),
    snr = abs(mean(get(dep_var), na.rm = T))/sd(get(dep_var), na.rm = T),
    rsd = sd(get(dep_var), na.rm = T)/abs(mean(get(dep_var), na.rm = T)))
# within_school_raw <- rbind.all.columns(within_school_raw, tmp)

tmpp <- tmp[-1] %>% 
  filter(within_school_sd > 0 & within_school_mean != 0) %>%
  psych::describe(omit = T) %>%
  mutate(vars = paste(var, "-" ,trans))
# within_school_sum <- rbind.all.columns(within_school_sum, tmpp)



kbl(tmpp[-1], caption = paste("Descriptives of school-level", var, trans)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T) %>% 
  print()

# show in boxplot
plt <- ggplot(data = tmp, aes(x = rsd )) +
  geom_boxplot() +
  geom_point(aes(y = 0), color = coral) +
  ambition_theme +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_x_continuous(labels = scales::percent) +
  xlab(paste("%RSD", y_lab, "- RAW")) # % relative standard deviation
print(plt)

```

# Student-level predictors

```{r, echo = F, results='asis',fig.align='center', warning=FALSE}

# filter to create predictor dataset #

x <- pup[laestab %in% list_laestab]
x[, status := fifelse(laestab %in% unique(est_treated[, "laestab"]), "treated", "untreated")]
x[, idx_treat := fifelse(laestab %in% unique(est_treated[, "laestab"]), TRUE, FALSE)]
x[, idx_donor := fifelse(laestab %in% unique(est_treated[, "laestab"]), FALSE, TRUE)]
x[, time_period := insert_slash(time_period)]

# create dict with var names and meanings #

# determine which vars to plot
vars <- names(x)[grepl("pnpup|ks2", names(x))]
vars <- vars[!grepl("_t", vars)]

# create df
dict <- data.frame(var = vars)

# add explanation
dict$explanation <- c("% pupils female",
                      "% pupils eligible for FSM (census)",
                      "% pupils eligible for FSM (SPT)",
                      "% pupils eligible for FSM ever (SPT)",
                      "% EAL pupils",
                      "% pupils with White British ethnic origin",
                      "% pupils with Black ethnic origin",
                      "% pupils with Asian ethnic origin",
                      "% SEND pupils",
                      "Percentile KS2 average",
                      "Z score KS2 average"
)

# create labels #
x_lab <- "Academic year"
group_var = "time_period"

transforms <- c("RAW")

# debug
var = vars[1]
trans = transforms[1]

for (var in vars) {
  
  y_lab <- dict$explanation[dict$var == var]
  
  cat("\n## ", y_lab, "\n")
  cat("\n\n")
  
  for (trans in transforms) {
    
    cat("\n#### ", stringr::str_to_sentence(trans), "data\n")
    cat("\n\n")
    
    <<working_chunk>>
      
    cat("\n\n")
    
  }
  
}

```



# Teacher-level predictors

```{r, echo = F, results='asis',fig.align='center', warning=FALSE}

# filter to create predictor dataset #

x <- swf[laestab %in% list_laestab]
x[, status := fifelse(laestab %in% unique(est_treated[, "laestab"]), "treated", "untreated")]
x[, idx_treat := fifelse(laestab %in% unique(est_treated[, "laestab"]), TRUE, FALSE)]
x[, idx_donor := fifelse(laestab %in% unique(est_treated[, "laestab"]), FALSE, TRUE)]
x[, time_period := insert_slash(time_period)]

# create dict with var names and meanings #

# determine which vars to plot
vars <- names(x)[grepl("fte_perc|age_avg|business|admin", names(x))]
vars <- names(x)[grepl("fte_perc|age_avg|admin", names(x))]
vars <- vars[!grepl("hc", vars)]


# create labels #
x_lab <- "Academic year"
group_var = "time_period"

transforms <- c("RAW")

# debug
var = vars[2]
trans = transforms[1]

for (var in vars) {
  
  y_lab <- gsub("fte_perc", "FTE %", stringr::str_to_sentence(gsub("_", " ", var)))

  cat("\n## ", y_lab, "\n")
  cat("\n\n")
  
  for (trans in transforms) {
    
    cat("\n#### ", stringr::str_to_sentence(trans), "data\n")
    cat("\n\n")
    
    <<working_chunk>>
      
    cat("\n\n")
    
  }
  
}

```


