---
title: "St Peters - DV and predictors"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    self_contained: true
---


Donor pool equal to St Peters with respect to:  

- Phase of education  
- Region  
- Level of urbanicity  
- Denomination  
- Completeness of observations on the outcome measure  
- Note: Boarding schools are excluded from donor pool  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = F)

options(scipen = 999)
# empty work space
rm(list = ls())
gc()

# load libraries
library(kableExtra)
library(dplyr)
library(data.table)
library(ggplot2)

# Define the base directory
dir <- getwd()
dir <- gsub("/02_scm/filtering_v1", "", dir)

# source functions
devtools::source_url("https://github.com/stefaniemeliss/scm_feasibility/blob/main/functions.R?raw=TRUE")

# Load and execute the process_data.R script
source(file = file.path(dir, "00_process", "03_process_data_st_peters_v1.R"))

# add status
df$status <- ifelse(df$laestab == id_treated, "treated", "untreated")
df$idx_treat <- ifelse(df$laestab == id_treated, TRUE, FALSE)
df$idx_donor <- ifelse(df$laestab == id_treated, FALSE, TRUE)

unique(df$time_period)

# copy data #
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_swf_nat_reg.csv"), dir_data, overwrite = T)

# load data #

nat <- fread(file.path(dir_data, "data_swf_nat_reg.csv"))

# format national level data

nat <- nat %>% 
  filter(school_type == "State-funded secondary") %>%
  mutate(level = ifelse(grepl("London", region_name), "London",
                        ifelse(region_name == "England", "National", "Not London")),
         # remove the last two digits
         time_period = as.numeric(substr(time_period, 0, 4)),
         region_name = factor(region_name, levels = c("England", 
                                                      "North East", "North West", "Yorkshire and The Humber", 
                                                      "East Midlands", "West Midlands", "East of England", "South East", "South West", 
                                                      "Inner London", "Outer London")))
```


```{r working_chunk, echo=FALSE, eval=F}
df_plt = df

dep_var = var

# look at histogram by year
plt <- ggplot(data = df_plt, aes(x = get(dep_var))) + 
  geom_histogram(bins = 25) + 
  facet_wrap(~get(group_var)) + 
  ambition_theme + 
  ylab("Count") +
  xlab(paste(y_lab)) + theme(axis.text.x = element_blank())
print(plt)

# compute descriptives per year
out <- rbind(
  do.call("rbind",psych::describeBy(df_plt[, dep_var], group = df_plt[, group_var]))
)
# edit output
out$vars <- NULL
out <- round(out, 3)
# print output
kbl(out, caption = paste("Descriptives of variable", var)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T) %>%
  print()

# augmented Dickey-Fuller test
tseries::adf.test(na.omit(out$mean), k = 0) %>%
  print()


# plot overall time series
n_donors = length(unique(df_plt$laestab[df_plt$idx_donor]))

if (grepl("ratio", dep_var)) {
  # plot national and regional time series
  plt <- ggplot(data = nat, aes(x = time_period, y = get(dep_var), group = region_name)) +
    geom_line(data = nat[nat$level == "National", ], aes(col = region_name), linewidth =.8) + 
    geom_line(data = nat[nat$level == "Not London", ], aes(col = region_name)) + 
    geom_line(data = nat[nat$level == "London", ], aes(col = region_name)) + 
    ambition_theme + 
    facet_grid(rows = "geographic_level", scales = "free") +
    theme(legend.title = element_blank(), 
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylab(paste(y_lab)) + xlab(x_lab) +
    scale_color_manual(values = c(black, ambition_palette, black20, black40))
  print(plt)
  
  # add national average
  plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab)) +
    geom_line(data = df_plt[df_plt$idx_donor,], aes(col = paste("Donor schools"))) + 
    geom_line(data = df_plt[df_plt$idx_treat,], aes(col = "St Peters"), linewidth =.8) +
    geom_line(data = nat[nat$level == "National", ], aes(col = "National", group = region_name), linewidth =.8) + 
    ambition_theme + 
    theme(legend.title = element_blank(), 
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylab(paste(y_lab)) + xlab(x_lab) +
    labs(caption = paste0("Note. N = ", n_donors, " donor schools.")) +
    scale_color_manual(
      breaks=c("National", "St Peters", "Donor schools"),
      values=c("Donor schools" = navy40, "St Peters" = coral, "National" = navy))
  
} else {
  # don't add national count/sum as it messes up scaling
  plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab)) +
    geom_line(data = df_plt[df_plt$idx_donor,], aes(col = paste("Donor schools"))) + 
    geom_line(data = df_plt[df_plt$idx_treat,], aes(col = "St Peters"), linewidth =.8) +
    ambition_theme + 
    theme(legend.title = element_blank(), 
          axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylab(paste(y_lab)) + xlab(x_lab) +
    labs(caption = paste0("Note. N = ", n_donors, " donor schools.")) +
    scale_color_manual(
      breaks=c("St Peters", "Donor schools"),
      values=c("Donor schools" = navy40, "St Peters" = coral))
  
}
print(plt)


# Trellis plot
plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab, col = status, fill = status)) +
  geom_point() + 
  geom_line() +
  geom_area(alpha=0.6) +
  facet_wrap("laestab") +
  scale_color_manual(values = c(dominant_col, navy40)) + scale_fill_manual(values = c(dominant_col, navy40)) +
  ambition_theme + theme(legend.position = "none",  
                         axis.text.x = element_blank()
  ) +
  ylab(paste(y_lab)) +
  xlab(x_lab) #+ labs(caption = paste0("The treated school is ", id_treated, "."))
print(plt)

# plot yearly average
out[, group_var] <- row.names(out)
plt <- ggplot(data = out, aes(x = time_period, y = mean)) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = mean-1.96*se, ymax = mean+1.96*se), width=.2,
                position=position_dodge(.9)) +
  geom_line(group = 1) + 
  ambition_theme + theme(legend.position = "none",  
                         axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab(paste(y_lab)) +
  xlab(x_lab)
print(plt)

# within school stats
tmp <- df_plt %>% group_by(laestab) %>%
  summarise(#obs_per_school = sum(!is.na(get(dep_var))),
    vars = paste(var),
    within_school_mean = mean(get(dep_var), na.rm = T),
    within_school_sd = sd(get(dep_var), na.rm = T),
    snr = abs(mean(get(dep_var), na.rm = T))/sd(get(dep_var), na.rm = T),
    rsd = sd(get(dep_var), na.rm = T)/abs(mean(get(dep_var), na.rm = T)))
# within_school_raw <- rbind.all.columns(within_school_raw, tmp)

tmpp <- tmp[-1] %>% 
  filter(within_school_sd > 0 & within_school_mean != 0) %>%
  psych::describe(omit = T) %>%
  mutate(vars = paste(var))
# within_school_sum <- rbind.all.columns(within_school_sum, tmpp)



kbl(tmpp[-1], caption = paste("Descriptives of school-level", var)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T) %>% 
  print()

# show in boxplot
plt <- ggplot(data = tmp, aes(x = rsd )) +
  geom_boxplot() +
  geom_point(aes(y = 0), color = coral) +
  ambition_theme +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  scale_x_continuous(labels = scales::percent) +
  xlab(paste("%RSD", y_lab)) # % relative standard deviation
print(plt)

```

```{r dv, echo = F, results='asis',fig.align='center', warning=FALSE}
var <- "pupil_to_qual_teacher_ratio"
y_lab <-  stringr::str_to_sentence(gsub("_", " ", var))
x_lab <- "Academic year"
group_var = "time_period"

cat("\n## ", y_lab, "\n")
cat("\n\n")

<<working_chunk>>

```

```{r pred, echo = F, results='asis',fig.align='center', warning=FALSE}
# create dict with var names and meanings #

# determine which vars to plot
vars <- names(x)[grepl("pnpup|ks2", names(x))]
vars <- vars[!grepl("_t", vars)]

# create df
dict <- data.frame(var = vars)

# add explanation
dict$explanation <- c("% pupils female",
                      "% pupils eligible for FSM (census)",
                      # "% pupils eligible for FSM (SPT)",
                      # "% pupils eligible for FSM ever (SPT)",
                      "% EAL pupils",
                      "% pupils with White British ethnic origin",
                      "% pupils with Black ethnic origin",
                      "% pupils with Asian ethnic origin",
                      "% SEND pupils",
                      # "Percentile KS2 average",
                      "Z score KS2 average"
)

# create labels #
x_lab <- "Academic year"
group_var = "time_period"

transforms <- c("RAW")

# debug
var = vars[1]
trans = transforms[1]

for (var in vars) {
  
  y_lab <- dict$explanation[dict$var == var]
  
  cat("\n## ", y_lab, "\n")
  cat("\n\n")
  
  
  <<working_chunk>>
    
  cat("\n\n")
  
}

```

