---
title: "Treated schools: workforce census"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)
# empty work space
rm(list = ls())
gc()

# load libraries
library(kableExtra)
library(dplyr)
library(data.table)
library(ggplot2)

# create function to source code
source_code <- function(root_dir_name = "code", target_repo = "helper_functions", branch = "main", file_name = "file.R") {
  
  # construct URL
  git_url <- paste0("https://raw.githubusercontent.com/stefaniemeliss/", target_repo, "/", branch, "/", file_name)
  
  # attempt to download from github
  tempp_file <- tempfile(fileext = ".R")
  message <- curl::curl_download(git_url, tempp_file, quiet = F)
  
  if(!grepl("Error", message)) {
    
    # if successful, source file
    source(tempp_file)
    remove(tempp_file)
    
  } else { # load local copy of file
    
    # Get the current working directory
    current_dir <- getwd()
    
    # Split the current directory into its components
    dir_components <- strsplit(current_dir, "/")[[1]]
    
    # Identify the root directory dynamically based on the provided root directory name
    root_index <- which(dir_components == root_dir_name)
    if (length(root_index) == 0) {
      stop(paste("Root directory", root_dir_name, "not found in the current path"))
    }
    root_dir <- do.call(file.path, as.list(dir_components[1:root_index]))
    
    # Identify the subdirectory one level below the root and construct its absolute path
    project_repo <- dir_components[root_index + 1]
    dir <- file.path(root_dir, project_repo)
    
    if (target_repo != project_repo) {
      dir <- gsub(project_repo, target_repo, dir) 
    }
    
    # Construct the full file path
    file_path <- file.path(dir, file_name)
    
    # Print the directory and file path for debugging
    print(paste("Directory:", dir))
    print(paste("File path:", file_path))
    
    # Source the file into the parent frame
    source(file_path, local = parent.frame())
  }
}

# source functions
source_code(target_repo = "scm_feasibility", file_name = "functions.R")

# Define the base directory
dir <- get_directory()
dir_data <- file.path(dir, "data")
dir_misc <- file.path(dir, "misc")

# get file stem name
out_file <- paste0(get_file_stem(), "_out.csv")
#if(file.exists(out_file)) file.remove(out_file)


# copy data #
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_swf.csv"), dir_data, overwrite = T)
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_spt_ks4.csv"), dir_data, overwrite = T)
file.copy(
  file.path(gsub("scm_feasibility", "edu_stats", dir_data), "data_establishments_search.csv"), dir_data, overwrite = T)

# load data #

swf <- fread(file.path(dir_data, "data_swf.csv"))
pup <- fread(file.path(dir_data, "data_spt_ks4.csv"))
est <- fread(file.path(dir_data, "data_establishments_search.csv"), na.strings = "")


# process data establishments #

# St. Peters
laestab_stp <- 3344650

# Highcrest Academy
laestab_hca <- 8254001

# Dixon schools
dix <- fread(file.path(dir_misc, "Dixons Linked establishments.csv"))
dix$`Joined date` <- as.Date(dix$`Joined date`, format =  "%d/%m/%Y")
dix$laestab <- gsub("/", "", dix$LAESTAB)

# get establishment data from treated schools
list_laestab <- c(laestab_stp, laestab_hca, dix$laestab)

est_treated <- est %>% 
  filter(laestab %in% list_laestab) %>%
  mutate(school = "treated") %>% 
  as.data.frame()

swf <- swf %>%
  filter(laestab %in% list_laestab) 

pup <- pup %>%
  filter(laestab %in% list_laestab) %>%
  select(time_period, laestab, p8mea)

df <- swf %>%
  full_join(., pup, by = c("time_period", "laestab")) %>%
  mutate(time_period = insert_slash(time_period),
         laestab = factor(laestab)) %>%
  as.data.frame()

```

```{r working_chunk, echo=FALSE, eval=F}

df_plt <- df 
dep_var = var


# compute descriptives per school
out <- rbind(
  do.call("rbind",psych::describeBy(df_plt[, dep_var], group = df_plt[, group_var]))
)
# edit output
out$vars <- NULL
out <- round(out, 3)
# print output
kbl(out, caption = paste("Descriptives of variable", var)) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T) %>%
  print()


# plot overall time series
plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab, col = laestab)) +
  geom_line() + 
  ambition_theme + 
  theme(legend.title = element_blank(), 
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylab(y_lab) + xlab(x_lab) +
  scale_colour_manual(values = as.vector(pals::polychrome(length(list_laestab))))
print(plt)


# Trellis plot
plt <- ggplot(data = df_plt, aes(x = time_period, y = get(dep_var), group = laestab, col = laestab, fill = laestab)) +
  geom_point() + 
  geom_line() +
  geom_area(alpha=0.6) +
  facet_wrap("laestab") +
  ambition_theme + 
  theme(legend.position = "none",  
        axis.text.x = element_blank()) +
  ylab(y_lab) + xlab(x_lab) +
  scale_colour_manual(values = as.vector(pals::polychrome(length(list_laestab)))) +
  scale_fill_manual(values = as.vector(pals::polychrome(length(list_laestab))))
print(plt)

```


```{r, echo = F, results='asis',fig.align='center', warning=FALSE}
# determine id cols
id_cols <- c("urn", "laestab", "time_period")

# determine which vars to plot
vars <- names(df)[sapply(df, is.numeric)]
vars <- vars[!vars %in% c(id_cols, "old_la_code", "laestab")]

vars <- vars[!grepl("urn_|fte|hc", vars)]


# define DV and label
var <- "fte_classroom_teachers"
x_lab <- "Academic year"
group_var = "laestab"

# debug
var = vars[1]

for (var in vars) {
  
  y_lab <- stringr::str_to_sentence(gsub("_", " ", var))
  
  cat("\n## ", y_lab, "\n")
  cat("\n\n")
  
  
  <<working_chunk>>
    
    cat("\n\n")
    
  
}

```




