---
title: "Synth vs gsynth"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

This tutorial shows how to estimate synthetic control models (SCM) using the Synth and the gsynth packages for R. 


```{r}
library(Synth)
library(gsynth)
```

The tutorial will use simulated data for 10 states and 30 years. State A receives the treatment T = 20 after year 15.

```{r}
set.seed(1)
year <- rep(1:30, 10) 
state <- rep(LETTERS[1:10], each = 30)
X1 <- round(rnorm(300, mean = 2, sd = 1), 2)
X2 <- round(rbinom(300, 1, 0.5) + rnorm(300), 2)
Y <- round(1 + 2*X1 + rnorm(300), 2)
df <- as.data.frame(cbind(Y, X1, X2, state, year))
df$Y <- as.numeric(as.character(df$Y))
df$X1 <- as.numeric(as.character(df$X1))
df$X2 <- as.numeric(as.character(df$X2))
df$year <- as.numeric(as.character(df$year))
df$state.num <- as.numeric(as.factor(df$state))
df$state <- as.character(df$state)
df$T <- ifelse(df$state == "A" & df$year >= 15, 1, 0)
df$Y <- ifelse(df$state == "A" & df$year >= 15, df$Y + 20, df$Y)

str(df)
head(df)
```
### Use Synth to estimate SCM

```{r}
dataprep.out <-
        dataprep(df,
                 predictors = c("X1", "X2"),
                 dependent     = "Y",
                 unit.variable = "state.num",
                 time.variable = "year",
                 unit.names.variable = "state",
                 treatment.identifier  = 1,
                 controls.identifier   = c(2:10),
                 time.predictors.prior = c(1:14),
                 time.optimize.ssr     = c(1:14),
                 time.plot             = c(1:30)
                 )

# Run synth
synth.out <- synth(dataprep.out)
```
```{r}
# Get result tables
print(synth.tables   <- synth.tab(
        dataprep.res = dataprep.out,
        synth.res    = synth.out)
      )
```

```{r}
path.plot(synth.res    = synth.out,
          dataprep.res = dataprep.out,
          Ylab         = c("Y"),
          Xlab         = c("Year"),
          Legend       = c("State A","Synthetic State A"),
          Legend.position = c("topleft")
)

abline(v   = 15,
       lty = 2)
```

```{r}
gaps.plot(synth.res    = synth.out,
          dataprep.res = dataprep.out,
          Ylab         = c("Gap"),
          Xlab         = c("Year"),
          Ylim         = c(-30, 30),
          Main         = ""
)

abline(v   = 15,
       lty = 2)
```

### Use gsynth to estimate SCM

```{r}
gsynth.out <- gsynth(Y ~ T + X1 + X2, data = df,
                     index = c("state","year"), force = "two-way", 
                     CV = TRUE, r = c(0, 5), se = TRUE, 
                     inference = "parametric", nboots = 1000,
                     parallel = TRUE)
```
```{r}
gsynth.out$wgt.implied

synth.tables$tab.w
```

```{r}
plot(gsynth.out, type = "raw")
```


```{r}
plot(gsynth.out)
```

```{r}
plot(gsynth.out, type = "counterfactual")
```

```{r}
plot(gsynth.out, type = "counterfactual", raw = "all") # shows estimations for the control cases
```

```{r}
plot(gsynth.out, type = "gap")
```

